-- VHDL Entity MIPS.MIPS_tb.symbol
--
-- Created:
--          by - kolaman.UNKNOWN (KOLAMAN-PC)
--          at - 09:22:45 17/02/2013
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2011.1 (Build 18)
--


ENTITY MIPS_tb IS
-- Declarations

END MIPS_tb ;

--
-- VHDL Architecture MIPS.MIPS_tb.struct
--
-- Created:
--          by - kolaman.UNKNOWN (KOLAMAN-PC)
--          at - 09:22:45 17/02/2013
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2011.1 (Build 18)
--
LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;

LIBRARY work;

ARCHITECTURE struct OF MIPS_tb IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL SW,LEDG,LEDR :STD_LOGIC_VECTOR (7 DOWNTO 0) := "00000000";
   SIGNAL HEX0,HEX1,HEX2,HEX3: STD_LOGIC_VECTOR (6 DOWNTO 0) := "0000000";
   SIGNAL KEY	 			: STD_LOGIC_VECTOR (2 DOWNTO 0) := "000";
   SIGNAL clock           : STD_LOGIC;
   SIGNAL reset           : STD_LOGIC;


   -- Component Declarations
   COMPONENT MIPS
   PORT(
		rst_in          : IN  STD_LOGIC;
		clk_24MHz             : IN  STD_LOGIC;
		SW   : IN  STD_LOGIC_VECTOR (7 DOWNTO 0);
		LEDG : OUT STD_LOGIC_VECTOR (7 DOWNTO 0);
		LEDR : OUT STD_LOGIC_VECTOR (7 DOWNTO 0);
		KEY	 : IN  STD_LOGIC_VECTOR (2 DOWNTO 0);
		HEX0 : OUT STD_LOGIC_VECTOR (6 DOWNTO 0);   -- converted to 7-seg
		HEX1 : OUT STD_LOGIC_VECTOR (6 DOWNTO 0);   -- converted to 7-seg
		HEX2 : OUT STD_LOGIC_VECTOR (6 DOWNTO 0);   -- converted to 7-seg
		HEX3 : OUT STD_LOGIC_VECTOR (6 DOWNTO 0) -- converted to 7-seg	
	);
   END COMPONENT;
   COMPONENT MIPS_tester
   PORT (
      clock           : OUT    STD_LOGIC ;
      reset           : OUT    STD_LOGIC 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : MIPS USE ENTITY work.mips;
   FOR ALL : MIPS_tester USE ENTITY work.mips_tester;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : MIPS
      PORT MAP (
         rst_in           => reset,
         clk_24MHz           => clock,
        SW   => SW,
		LEDG => LEDG,
		LEDR => LEDR,
		HEX0 => HEX0 ,  -- converted to 7-seg
		HEX1 =>  HEX1,  -- converted to 7-seg
		HEX2 =>  HEX2,  -- converted to 7-seg
		HEX3 => HEX3,	-- converted to 7-seg
		KEY	 => KEY
      );
   U_1 : MIPS_tester
      PORT MAP (
         clock           => clock,
         reset           => reset
      );
	  
	  
	  
	tb: process
	begin
      wait for 3000 ns;
      KEY(0) <= '1', '0' after 1035 ns;
      wait;
	end process;

END struct;
